defaults:
  - _self_

seed: 42

dataset:
  name: "danp27/norobots_sft"
  split: "train"
  text_field: "formatted_text"
  add_bos_eos: true
  num_proc: 1
  sample_size: 100  # set to an int for quick smoke tests

data_builder:
  enabled: true
  datasets:
    - name: "danp27/norobots_sft"
      split: "train"
      proportion: 0.5
      sample_size: null
      text_field: null
      add_bos_eos: null
      num_proc: null
    - name: "./data/formatted_data/dolly"
      split: "train"
      proportion: 0.5
      sample_size: null
      text_field: null
      add_bos_eos: null
      num_proc: null


data_collator:
  pack_length: 2048
  use_custom_packed : false

model:
  builder:
    model_name: "meta-llama/Llama-3.2-1B"
    tokenizer_name: null 
    load_in_4bit: false
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_compute_dtype: "bfloat16"
    bnb_4bit_use_double_quant: true
    device_map: "auto"
    gradient_checkpointing: true
    use_cache: false
    prepare_kbit_training: true
    require_grads: true
    max_seq_length: 4096
    use_unsloth: false
    unsloth_path: null
  lora:
    r: 16
    lora_alpha: 32
    lora_dropout: 0.0
    bias: "none"
    task_type: "CAUSAL_LM"
    target_modules:
      - q_proj
      - k_proj
      - v_proj
      - o_proj
      - gate_proj
      - up_proj
      - down_proj
      # - embed_tokens
      # - lm_head

training_args:
  output_dir: "./outputs/train_llama"
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 4
  logging_steps: 1
  learning_rate: 2e-5
  num_train_epochs: 1
  save_steps: 100
  save_total_limit: 1
  report_to: "wandb"
  bf16: true
  fp16: false
  optim: "adamw_torch"
  lr_scheduler_type: "linear"
  warmup_ratio: 0.03
  gradient_checkpointing: true

wandb:
  enabled: false
  project: "ContinualPretrainRo"
  run_name: "test1"

hydra:
  run:
    dir: "."
  sweep:
    dir: "multiruns"
    subdir: ${hydra.job.num}
